version: '3.1'

services:

  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
      - queue
    environment:
      - DD_AGENT_HOST=datadog
    volumes:
      - ./datadog/var/run:/var/run/datadog:ro

  db:
    image: mongo
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

  cache:
    image: redis
    volumes:
      - cache-data:/data

  queue:
    image: rabbitmq:management
    volumes:
      - queue-data:/var/lib/rabbitmq

  worker:
    build: worker
    depends_on:
      - queue
      - db
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
    volumes:
      - ./datadog/var/run:/var/run/datadog:ro

  poller:
    build: poller
    depends_on:
      - frontend
      - selenium
    volumes:
    - ./poller/screenshots:/screenshots

  selenium:
    image: selenium/standalone-chrome
    volumes:
    - /dev/shm:/dev/shm

  datadog:
    image: datadog/agent
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
      - ./datadog/var/run:/var/run/datadog
      - ./datadog/conf.d:/conf.d:ro
 
volumes:
  db-data:
  db-config:
  cache-data:
  queue-data:
